README.md
[Just a minor suggestion]
Also, a question:
should I replace the URL https://github.com/coq-community/manifesto/tree/master/templates with https://github.com/coq-community/templates for the two "templates" hyperlinks in the docker-coq wiki?
* https://github.com/coq-community/docker-coq/wiki/CI-setup#travis-ci-config
* https://github.com/coq-community/docker-coq/wiki/CI-setup#related-links
(BTW I've seen there is https://github.com/coq-community/manifesto/pull/69, but I don't know what is the status of this PR…)
=> docs(README.md): Fix the "example files" hyperlink

README.md.mustache
Related issue: #1 
CircleCI is getting popular in Coq projects in and outside the community:
- [Cérès](https://github.com/Lysxia/coq-ceres/blob/master/.circleci/config.yml)
- [Ext-Lib](https://github.com/coq-community/coq-ext-lib/blob/master/.circleci/config.yml)
- [QuickChick](https://github.com/QuickChick/QuickChick/blob/8.10/.circleci/config.yml)
- [Reduction Effects](https://github.com/coq-community/reduction-effects/blob/master/.circleci/config.yml)
- [Simple IO](https://github.com/Lysxia/coq-simple-io/blob/master/.circleci/config.yml)
- [Software Foundations Chinese Translation](https://github.com/Coq-zh/SF-zh/blob/master/.circleci/config.yml)
+ The English version (in private repo) also uses CircleCI.
As suggested in https://github.com/coq-community/templates/issues/1#issuecomment-5 …
=> CircleCI badge in README template

README.md
As requested by @Zimmi48 in https://github.com/coq-community/manifesto/pull/95
=> avoid referring to template-examples in manifesto repo

README.md.mustache
(a detail in the README.md template)
=> Add missing (implied) .git suffix in the "git clone" command

.travis.yml.mustache
This PR improves the `.travis.yml` for several minor or not-so-minor issues, now spotted automatically by Travis CI's `Build config validation`
=> Fix Travis CI "Build config validation" errors

README.md, README.md.mustache, coq-action.yml.mustache, generate.sh
This PR is a follow-up of a discussion with @Zimmi48, and of the release of docker-coq-action:
https://github.com/coq-community/docker-coq-action/releases/tag/v1.0.0
see the commit messages for more details
=> Update generate & Add template for GitHub container action

.github/workflows/lint.yml, coq-action.yml.mustache, coq.opam.mustache, extracted.opam.mustache, ref.yml
We should clarify many more keys _e.g._ I don't know how to write `tested_coq_nix_versions` in my `meta.yml`.
Also, the [supported tags](https://github.com/coq-community/docker-coq/wiki#supported-tags) wiki seems outdated after https://github.com/coq-community/docker-base/issues/4#issuecomment-597894289.
=> ref: clarify keys with examples

.travis.yml.mustache, config.yml.mustache, coq-action.yml.mustache, generate.sh, ref.yml
=> Add CircleCI template

.travis.yml.mustache, config.yml.mustache, ref.yml
Motivation: https://github.com/coq-community/reglang/pull/13#discussion_r432364516
After this change, by default extra-dev is only included when building on Coq dev.
=> feat: Add ci_extra_dev

.travis.yml.mustache, ref.yml
This PR implements the enhancement proposed in #39
=> allow specifying the Docker repo for 'tested_coq_opam_versions' for use in .travis.yml

coq-action.yml.mustache
* The coq-action now behaves closer like Travis CI and its pr builds.
* The configuration still prevents the "double-build" concern when one opens a PR from an upstream-repo branch.
=> feat: Enable GitHub Action builds for any PR

coq-action.yml.mustache, ref.yml
Follow-up of https://github.com/coq-community/templates/pull/57
=> allow specifying the Docker repo for 'tested_coq_opam_versions' for use in coq-action.yml

README.md.mustache, coq.opam.mustache, dune-project.mustache, dune.mustache, ref.yml
Dune is activated by a simple `dune: true` as per #38. I have no idea how to add dune support for Nix builds, but on the other hand I use regular make builds in Nix for all my personal projects (to find errors in both dune and make builds).
Fixes #38.
=> dune support in README.md and coq.opam

README.md.mustache, index.md.mustache, ref.yml
This PR adds a list of names of contributors. This is to give credit to people who contributed to a library without making them authors outright. Currently, this is displayed as two separate lists in `README.md` and as a joint list (as per the existing "Authors and Contributors" heading) in `index.md`.
=> Support adding more info after authors (e.g. a list of contributors).

README.md.mustache, index.md.mustache, ref.yml
This PR turns the `coqdoc_index` variable into a URL relative to the (usual) position of the `index.html` file. The main rationale is that this allows the `coqdoc` badge to actually point to the documentation rather than the project description page while generating a reasonable `index.md` that points to the same place. 
It also removes the alternative sentence "The coqdoc presentations of the source files from releases can be browsed online.", because this sentence makes no sense unless one manually edits `index.md` (or `index.html`), in which case one can easily also add a description of the added content.
=> turn coqdoc_index into relative URL

README.md.mustache, ref.yml
Fixes coq-community/templates#55
=> Allow to define a reference branch other than `master'

index.md.mustache
The header link is in the HTML part of the file, so the Markdown syntax is not compiled.
E.g. compare the two following GitHub pages:
- generic-environments ([page](http://coq-community.org/generic-environments/)) ([markdown](https://raw.githubusercontent.com/coq-community/generic-environments/master/index.md)) which is generated from this template, and
- lttt ([page](https://aerabi.github.io/lttt/)) ([markdown](https://raw.githubusercontent.com/aerabi/lttt/master/index.md)) which was generated from the template, and then [fixed the same way](https://github.com/aerabi/lttt/commit/c66cb57c652dada546077e6adda71b5320c5cbd8).
=> Fix header link in index.md

README.md
To bikeshed about names is always a perilous activity, but I think we have to do something about "Coq-community Templates", since it's too specific and not descriptive enough. 
How about: "Coq Project Templates"?
=> change name of project in README

generate.sh
Do not generate the corresponding files if they were not asked for.
Put them in the right directory.
The fact that our recommended tool (`generate.sh`) has been generating unconditionally the `dune-project`, `dune` and `index.md` files without moving them to the appropriate directory has been a source of confusion for a long time (especially for `index.md`).
=> Fix generate.sh to look for values of coqdoc and dune.

docker-action.yml.mustache, nix-action.yml.mustache, ref.yml
This enables scheduled runs for actions-based CI via a new variable called `ci_cron_schedule`. As discussed in #77, there is no default value to keep everyone from using the same value. 
closes: #77
=> introduce 'ci_cron_schedule' for scheduled CI actions

nix-action.yml.mustache
EDIT:
- To simplify, I kept only the first commit / first part for this PR. The next one can be reviewed separately later on.
- I've now updated this PR to be more similar to what is done in coq-community/coq-nix-toolbox#55.
The goal is to avoid ever rebuilding the same thing twice in CI. When a PR is submitted from a fork, if it has to build a dependency, we don't want to waste this precious build time by discarding the build output. And if the PR is merged as is, it shouldn't be needed to rebuild anything once merged in the base branch (if it hasn't changed).
Use the `pull_request_target` event instead of the `pull_request` event to have access to secret environment variables in all cases. This is safe (no risk of linking the secret variables) even with untrusted code because …
=> [Nix Action] Deploy to Cachix even for PR from forks.

nix-action.yml.mustache
I just realized by analyzing a strange success in an aac-tactics overlay that Nix CI was completely broken for PRs since #107 because I stupidly forgot to update the `actions/checkout@v2` step.
The second commit is a port of coq-community/coq-nix-toolbox#81. I'm taking advantage that there will need to be an update of projects relying on Nix CI to do this change in passing.
I've tested that this works on the above-mentioned aac-tactics overlay.
@palmskog I can take care of updating the 9 coq-community projects using the `nix-action` tag. If you know of some other projects (e.g., external to coq-community) that also use this template, please make sure they are updated as well.
=> Fix and update Nix CI

docker-action.yml.mustache
The `textbook/git-checkout-submodule-action` action had been deprecated for a while and has now stopped working (from the breakage observed in the VST repository). This fix corresponds to the one made in https://github.com/PrincetonUniversity/VST/pull/535 (which seems to have succeeding in fixing the issue) and to a previous similar change that I had done in the Nix CI template. The fact that we didn't detect it on the Coq-community side is just because AFAICT the few Coq-community projects that fetch submodules are all on Circle CI rather than GitHub Actions.
=> Fix submodule fetching for Docker-Coq-Action template.

README.md
As reported by Laurent Théry on the Zulip, the `mustache` obtained via `opam install mustache` does not work, so we warn against it in the README.
=> warn about opam mustache in README.md

README.md.mustache, index.md.mustache, ref.yml
ORCIDs are a good way to track authors independently of their (possibly ambiguous) name. I implement the ORCID display in `README.md` and `index.md` following the [brand guidelines](https://info.orcid.org/brand-guidelines/).
=> add orcid as author attribute, use README.md and index.md templates

.github/workflows/lint.yml, docker-action.yml.mustache, nix-action.yml.mustache
This should be all we need, right @Zimmi48? More context [here](https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs-.26-users/topic/Deprecations.20for.20Docker-Coq-Action/near/309567584).
cc: @erikmd
=> use checkout@v3 to avoid Actions deprecations

nix-action.yml.mustache
This does the same changes as https://github.com/coq-community/coq-nix-toolbox/pull/135. Since it was needed for Nix CI using the Coq Nix Toolbox directly, it is likely that this is also needed for users through the templates.
=> Update cachix actions in Nix CI.

.travis.yml.mustache, nix-action.yml.mustache
Now that HTTP redirects do not work anymore on coq.inria.fr.
cc @palmskog 
We will need to update the projects that rely (or relied) on this template (see https://github.com/topics/nix-action):
And beyond Coq-community, in the projects:
=> Fix links to Coq Nix Toolbox.

index.md.mustache, ref.yml
Motivated by https://github.com/coq-community/templates/pull/74#issuecomment-745973411.
`index.md` currently has no customizable entries. Should we reuse `documentation` in README or create a new field?
=> feat: Add index_documentation

nix-action.yml.mustache
Hi, I believe I spotted a bug:
with the `meta.yml` snippet
```yml
tested_coq_nix_versions:
- coq_version: 'v8.19'
extra_dev_dependencies:
- nix_name: mathcomp
dev_version: 'mathcomp-2.2.0'
```
I was getting
```
matrix:
overrides:
- 'coq = "v8.19"; mathcomp = mathcomp-2.2.0'
```
instead of
```
matrix:
overrides:
- 'coq = "v8.19"; mathcomp = "mathcomp-2.2.0"'
```
Cc @Zimmi48 Does my patch look good to you?
=> fix(nix): Add missing quotes for dev_version if custom value

docker-action.yml.mustache
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Docker Action: checkout v4

index.md.mustache
The current link yields 404 Not Found.
The proposed link comes from an unofficial Gist: https://gist.github.com/johan/1007813 .
Tested in https://coq-community.org/coq-ext-lib/
=> index.md: replace Octocat URL

.travis.yml.mustache, config.yml.mustache, docker-action.yml.mustache, ref.yml
In reference to issue #134 .
I was hoping for some guidance on if further changes would be needed for the `tested_coq_nix_versions` and `extracted_tested_coq_opam_versions`?
Additionally, in the travis yml line 94 I left packages as `coq-`, does this seem reasonable or should it be `rocq-`?
=> Adding Rocq Opam Version Support
