rocq-community/templates

- README.md.mustache
- coq.opam.mustache
Allow many related publications, doi can be for project, allow setting version in opam files.
> README and opam template improvements

- default.nix.mustache
> default.nix: COQLIB -> COQMF_COQLIB

- README.md
* Address part of coq-community/templates#14
> docs: Add a note on ruby-mustache

- ref.yml
> document meta.yml

- .travis.yml.mustache
- README.md.mustache
- coq-action.yml.mustache
- generate.sh
- ref.yml
> separate opam_name from shortname

- README.md
- generate.sh
> feat: generate specific files

- README.md
- README.md.mustache
First step toward solving #40.
> Move from Gitter to Zulip in README and README template.

- README.md.mustache
As mentioned in https://github.com/coq-community/templates/commit/e506a07d2d00077df2e368e48287c6091d900b6a#r37736651
> README: more generic coqdoc link

- index.md.mustache
- ref.yml
> feat: Add coqdoc_index

- README.md.mustache
- config.yml.mustache
- coq-action.yml.mustache
- ref.yml
> README: include submodules in clone

- README.md
I suggest to replace the game of `cd` with a `mktemp`.
(and suggest that nix users use mustache in a nix shell)
> cd -> mktemp

- LICENSE
- README.md
> License all repository content under the Unlicense

- config.yml.mustache
- ref.yml
> Specify Docker repo in CircleCI

- README.md.mustache
- ref.yml
> make namespace optional for README.md.mustache

- README.md.mustache
- ref.yml
For projects from outside community.
As suggested in https://github.com/math-comp/analysis/pull/297 @Zimmi48
> add entry for associated chat room

- .travis.yml.mustache
- README.md
- README.md.mustache
- docker-action.yml.mustache
- generate.sh
- nix-action.yml.mustache
- ref.yml
This should be improved in the future but the current state provides parity with Travis CI.
Tested at coq-community/huffman#24.
> Add template for GitHub Action based on Nix.

- .travis.yml.mustache
- README.md.mustache
- config.yml.mustache
- coq.opam.mustache
- default.nix.mustache
- docker-action.yml.mustache
- dune-project.mustache
- dune.mustache
- extracted.opam.mustache
- index.md.mustache
- nix-action.yml.mustache
> Header for templates

- shell.nix
> Make nix-shell find mustache

- nix-action.yml.mustache
This should normally fix #103 but needs to be tested first.
> Account for schedule trigger in new Nix workflow.

- coq.opam.mustache
- ref.yml
on top of #92 
Tested on https://github.com/liyishuai/coq-http/blob/0c9f96ccd815c174a281b88fc2f38ad9af5d268c/coq-http.opam#L19
> Add install_flag

- config.yml.mustache
- ref.yml
on top of #92
Tested on liyishuai/coq-ext-lib@4d5557620ae32e55d0db1fe156739a3b8eafc4a3
> Add circleci_after_script

- config.yml.mustache
tested in QuickChick/QuickChick#240
> feat: CircleCI refine dependants test

- docker-action.yml.mustache
- ref.yml
tested in [coq-http](https://github.com/liyishuai/coq-http/blob/5177ab5729d5024bd6614fbc3a7eae9405031290/meta.yml#L58-L61)
> feat: GitHub Actions appendix

- docker-action.yml.mustache
- ref.yml
Tested in liyishuai/coq-async-test@5dbf8c5
> feat: GitHub Actions test dependencies

- README.md.mustache
As per https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
> fix CI status and ORCID images in README.md

- README.md.mustache
> README: Dune 3.6
